<div class="wp_hook_container">
  <div class="hhok-heading">Available Tags</div>
	<p class="hook-notes">You can use these tags in <strong>Get/post value</strong> to replace your value of post dynamically.</p>
  <table>
	<tr>
	  <td>_wpnonce</td>
		<td>%%_wpnonce%%</td>
	</tr>
	<tr>
	  <td>_wp_http_referer</td>
		<td>%%_wp_http_referer%%</td>
	</tr>
	<tr>
	  <td>user_ID</td>
		<td>%%user_ID%%</td>
	</tr>
	<tr>
	  <td>action</td>
		<td>%%action%%</td>
	</tr>
	<tr>
	  <td>originalaction</td>
		<td>%%originalaction%%</td>
	</tr>
	<tr>
	  <td>post_author</td>
		<td>%%post_author%%</td>
	</tr>
	<tr>
	  <td>post_type</td>
		<td>%%post_type%%</td>
	</tr>
	<tr>
	  <td>original_post_status</td>
		<td>%%original_post_status%%</td>
	</tr>
	<tr>
	  <td>referredby</td>
		<td>%%referredby%%</td>
	</tr>
	<tr>
	  <td>_wp_original_http_referer</td>
		<td>%%_wp_original_http_referer%%</td>
	</tr>
	<tr>
	  <td>post_ID</td>
		<td>%%post_ID%%</td>
	</tr>
	<tr>
	  <td>meta-box-order-nonce</td>
		<td>%%meta-box-order-nonce%%</td>
	</tr>
	<tr>
	  <td>closedpostboxesnonce</td>
		<td>%%closedpostboxesnonce%%</td>
	</tr>
	<tr>
	  <td>post_title</td>
		<td>%%post_title%%</td>
	</tr>
	<tr>
	  <td>samplepermalinknonce</td>
		<td>%%samplepermalinknonce%%</td>
	</tr>
	<tr>
	  <td>closedpostboxesnonce</td>
		<td>%%closedpostboxesnonce%%</td>
	</tr>
	<tr>
	  <td>content</td>
		<td>%%content%%</td>
	</tr>
	<tr>
	  <td>wp-preview</td>
		<td>%%wp-preview%%</td>
	</tr>
	<tr>
	  <td>hidden_post_status</td>
		<td>%%hidden_post_status%%</td>
	</tr>
	<tr>
	  <td>post_status</td>
		<td>%%post_status%%</td>
	</tr>
	<tr>
	  <td>hidden_post_password</td>
		<td>%%hidden_post_password%%</td>
	</tr>
	<tr>
	  <td>hidden_post_visibility</td>
		<td>%%hidden_post_visibility%%</td>
	</tr>
	<tr>
	  <td>visibility</td>
		<td>%%visibility%%</td>
	</tr>
	<tr>
	  <td>post_password</td>
		<td>%%post_password%%</td>
	</tr>
	<tr>
	  <td>original_publish</td>
		<td>%%original_publish%%</td>
	</tr>
	<tr>
	  <td>save</td>
		<td>%%save%%</td>
	</tr>
	<tr>
	  <td>post_format</td>
		<td>%%post_format%%</td>
	</tr>
	<tr>
	  <td>post_category</td>
		<td>%%post_category%%</td>
	</tr>
	<tr>
	  <td>newcategory</td>
		<td>%%newcategory%%</td>
	</tr>
	<tr>
	  <td>newcategory_parent</td>
		<td>%%newcategory_parent%%</td>
	</tr>
	<tr>
	  <td>_ajax_nonce-add-category</td>
		<td>%%_ajax_nonce-add-category%%</td>
	</tr>
	<tr>
	  <td>tax_input</td>
		<td>%%tax_input%%</td>
	</tr>
	<tr>
	  <td>newtag</td>
		<td>%%newtag%%</td>
	</tr>
	<tr>
	  <td>excerpt</td>
		<td>%%excerpt%%</td>
	</tr>
	<tr>
	  <td>trackback_url</td>
		<td>%%trackback_url%%</td>
	</tr>
	<tr>
	  <td>metakeyinput</td>
		<td>%%metakeyinput%%</td>
	</tr>
	<tr>
	  <td>metavalue</td>
		<td>%%metavalue%%</td>
	</tr>
	<tr>
	  <td>_ajax_nonce-add-meta</td>
		<td>%%_ajax_nonce-add-meta%%</td>
	</tr>
	<tr>
	  <td>advanced_view</td>
		<td>%%advanced_view%%</td>
	</tr>
	<tr>
	  <td>comment_status</td>
		<td>%%comment_status%%</td>
	</tr>
	<tr>
	  <td>ping_status</td>
		<td>%%ping_status%%</td>
	</tr>
	<tr>
	  <td>add_comment_nonce</td>
		<td>%%add_comment_nonce%%</td>
	</tr>
	<tr>
	  <td>_ajax_fetch_list_nonce</td>
		<td>%%_ajax_fetch_list_nonce%%</td>
	</tr>
	<tr>
	  <td>post_name</td>
		<td>%%post_name%% (This is the slug)</td>
	</tr>
	<tr>
	  <td>post_author_override</td>
		<td>%%post_author_override%%</td>
	</tr>
  </table>
</div>